# Generated by Django 4.1.2 on 2023-05-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile_picture',
            field=models.ImageField(default='admin/author1.jpg', upload_to=''),
        ),
    ]
