# Generated by Django 4.1.2 on 2023-06-09 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
